plugins {
    id 'org.springframework.boot' version '4.1.1'
    id "com.google.protobuf" version "0.10.0"
}

configurations {
    otelAgent
}

test {
    useJUnitPlatform {
        includeEngines 'junit-jupiter'
    }

    doFirst {
        jvmArgs "-javaagent:${configurations.otelAgent.singleFile}"
    }

    systemProperty 'otel.traces.exporter', 'logging'
    systemProperty 'otel.metrics.exporter', 'none'
    systemProperty 'otel.logs.exporter', 'none'
    systemProperty 'otel.service.name', 'junit5-tests'

    systemProperty 'otel.instrumentation.http.server.exclude-paths', '/actuator/**'
}

dependencies {
    otelAgent "io.opentelemetry.javaagent:opentelemetry-javaagent:2.30.0"

    implementation project(':on-demand:on-demand-spring-boot-starter-grpc')
    implementation project(':gcp:spring-boot-starter-gcp-grpc-spring')
    implementation project(':gcp:request-response-spring-boot-starter-gcp-grpc-spring')
    implementation project(':trace:server:correlation-id-trace-grpc-netty')
    implementation project(':request-response:request-response-spring-boot-autoconfigure-grpc-spring')

    implementation project(':trace:mdc-context-grpc-netty')

    implementation("io.grpc:grpc-api:$grpcVersion")
    implementation("io.grpc:grpc-core:$grpcVersion")
    implementation("io.grpc:grpc-context:$grpcVersion")
    implementation("io.grpc:grpc-stub:$grpcVersion")
    //implementation("io.grpc:grpc-inprocess:$grpcVersion")
    implementation("io.grpc:grpc-services:$grpcVersion")
    implementation("io.grpc:grpc-netty:$grpcVersion")
    implementation("io.grpc:grpc-util:$grpcVersion")
    implementation("org.springframework.boot:spring-boot-starter")

    testImplementation("org.springframework.boot:spring-boot-starter-test")

    // added due to grpc plugin dependency resolution problem
    testImplementation "org.junit.platform:junit-platform-launcher"

    testImplementation ("com.google.truth:truth:${googleTruthVersion}")
    testImplementation ("com.google.truth.extensions:truth-java8-extension:${googleTruthVersion}")

    testImplementation project(":test:test-logback-junit")
}

sourceSets {
    main {
        java {
            srcDirs '../gcp-grpc-spring-without-test-artifacts-example/src/main/java'
        }
        proto {
            srcDirs '../gcp-grpc-spring-without-test-artifacts-example/src/main/proto'
        }
        resources {
            srcDirs '../gcp-grpc-spring-without-test-artifacts-example/src/main/resources'
        }
    }
    test.java.srcDirs += "${protobuf.generatedFilesBaseDir}/test/java"
    test.java.srcDirs += "${protobuf.generatedFilesBaseDir}/test/grpc"
}

tasks.compileTestJava { dependsOn("generateTestProto") }

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${grpcProtobufVersion}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}
