Manifest-Version=1.0
Implementation-Title=io.micrometer#micrometer-core;1.16.5
Implementation-Version=1.16.5
Built-Status=release
Built-By=circleci
Built-OS=Linux
Build-Timezone=Etc/UTC
Build-Date-UTC=2026-04-13T13:44:12.927425635Z
Build-Date=2026-04-13_13:44:12
Gradle-Version=8.14.4
Module-Source=/micrometer-core
Module-Origin=git@github.com:micrometer-metrics/micrometer.git
Change=cf727d0
Full-Change=cf727d0a9605c1aea58c26c5e72fb9f6fe84df2a
Branch=HEAD
Build-Host=9e09bda18b43
Build-Job=deploy
Build-Number=67591
Build-Id=67591
Build-Url=https://circleci.com/gh/micrometer-metrics/micrometer/67591
Created-By=21.0.9+10-LTS (Eclipse Adoptium)
Module-Owner=tludwig@vmware.com
Module-Email=tludwig@vmware.com
X-Compile-Target-JDK=1.8
X-Compile-Source-JDK=1.8
Build-Java-Version=21