package no.entur.logging.cloud.protobuf.json.codedoutputstream;

import com.google.protobuf.ByteString;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.MessageLite;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.nio.ByteBuffer;

/**
 * Factory for {@linkplain CodedOutputStream}s which forward all writes to a {@linkplain CodedOutputStreamSink}, so that
 * the generated (reflection-free) serialization code of a message can drive JSON output.
 * <br><br>
 * The subclass of {@linkplain CodedOutputStream} is generated by {@linkplain ClassFileCodedOutputStreamFactory},
 * which uses the ClassFile API and so is compiled for Java 24. It is only loaded (by name) when running on Java 24+,
 * so that this module otherwise works on Java 17.
 * <br><br>
 * This feature is unavailable on older Java versions, and if the class cannot be loaded or defined (i.e. it was
 * removed when the jar was repackaged, or protobuf is loaded by a class loader which cannot see this class).
 */

final class JsonCodedOutputStreamFactory {

    static final int REQUIRED_JAVA_VERSION = 24;

    static final String CLASS_FILE_FACTORY = "no.entur.logging.cloud.protobuf.json.codedoutputstream.ClassFileCodedOutputStreamFactory";

    private static final MethodHandle CONSTRUCTOR;
    private static final Throwable UNAVAILABLE_CAUSE;

    static {
        MethodHandle constructor = null;
        Throwable cause = null;
        try {
            constructor = defineConstructor(Runtime.version().feature());

            // smoke test: resolves the sink interface from protobuf's class loader
            CodedOutputStream output = (CodedOutputStream) constructor.invokeExact((CodedOutputStreamSink) new NoopSink());
            output.writeInt32(1, 1);
        } catch (Throwable e) {
            constructor = null;
            cause = e;
        }
        CONSTRUCTOR = constructor;
        UNAVAILABLE_CAUSE = cause;
    }

    private JsonCodedOutputStreamFactory() {
    }

    /**
     * @param javaVersion the runtime's Java feature version
     * @return the constructor, of type (CodedOutputStreamSink)CodedOutputStream
     */

    static MethodHandle defineConstructor(int javaVersion) throws Throwable {
        if (javaVersion < REQUIRED_JAVA_VERSION) {
            // loading the class would fail with UnsupportedClassVersionError
            throw new UnsupportedOperationException("Requires Java " + REQUIRED_JAVA_VERSION + " or later, running on Java " + javaVersion);
        }
        Class<?> factory;
        try {
            factory = Class.forName(CLASS_FILE_FACTORY, true, JsonCodedOutputStreamFactory.class.getClassLoader());
        } catch (ClassNotFoundException e) {
            throw new IllegalStateException("Class " + CLASS_FILE_FACTORY + " not found. If the protobuf-json jar was repackaged "
                    + "(i.e. shaded or merged into an uber jar), make sure the class is kept; it is only loaded by name.", e);
        }
        MethodHandle defineConstructor = MethodHandles.lookup().findStatic(factory, "defineConstructor", MethodType.methodType(MethodHandle.class));
        return (MethodHandle) defineConstructor.invokeExact();
    }

    static boolean isAvailable() {
        return CONSTRUCTOR != null;
    }

    /**
     * @return the reason why this feature is unavailable, or null
     */

    static Throwable getUnavailableCause() {
        return UNAVAILABLE_CAUSE;
    }

    static CodedOutputStream create(CodedOutputStreamSink sink) {
        if (CONSTRUCTOR == null) {
            throw new IllegalStateException("Not available", UNAVAILABLE_CAUSE);
        }
        try {
            return (CodedOutputStream) CONSTRUCTOR.invokeExact(sink);
        } catch (RuntimeException | Error e) {
            throw e;
        } catch (Throwable e) {
            throw new IllegalStateException(e);
        }
    }

    private static class NoopSink implements CodedOutputStreamSink {
        @Override public void writeTag(int fieldNumber, int wireType) {}
        @Override public void writeInt32(int fieldNumber, int value) {}
        @Override public void writeUInt32(int fieldNumber, int value) {}
        @Override public void writeFixed32(int fieldNumber, int value) {}
        @Override public void writeUInt64(int fieldNumber, long value) {}
        @Override public void writeFixed64(int fieldNumber, long value) {}
        @Override public void writeBool(int fieldNumber, boolean value) {}
        @Override public void writeString(int fieldNumber, String value) {}
        @Override public void writeBytes(int fieldNumber, ByteString value) {}
        @Override public void writeByteArray(int fieldNumber, byte[] value) {}
        @Override public void writeByteArray(int fieldNumber, byte[] value, int offset, int length) {}
        @Override public void writeByteBuffer(int fieldNumber, ByteBuffer value) {}
        @Override public void writeRawBytes(ByteBuffer value) {}
        @Override public void writeMessage(int fieldNumber, MessageLite value) {}
        @Override public void writeMessageSetExtension(int fieldNumber, MessageLite value) {}
        @Override public void writeRawMessageSetExtension(int fieldNumber, ByteString value) {}
        @Override public void writeInt32NoTag(int value) {}
        @Override public void writeUInt32NoTag(int value) {}
        @Override public void writeFixed32NoTag(int value) {}
        @Override public void writeUInt64NoTag(long value) {}
        @Override public void writeFixed64NoTag(long value) {}
        @Override public void writeStringNoTag(String value) {}
        @Override public void writeBytesNoTag(ByteString value) {}
        @Override public void writeMessageNoTag(MessageLite value) {}
        @Override public void writeByteArrayNoTag(byte[] value, int offset, int length) {}
        @Override public void write(byte value) {}
        @Override public void write(byte[] value, int offset, int length) {}
        @Override public void writeLazy(byte[] value, int offset, int length) {}
        @Override public void write(ByteBuffer value) {}
        @Override public void writeLazy(ByteBuffer value) {}
        @Override public void flush() {}
        @Override public int spaceLeft() { return Integer.MAX_VALUE; }
        @Override public int getTotalBytesWritten() { return 0; }
    }
}
